//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : book dxsbvv b.java
//  @ Date : 15-04-2024
//  @ Author : 
//
//




/** */
public class book dxsbvv b
{
}
