//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : book.java
//  @ Date : 15-04-2024
//  @ Author : 
//
//




/** */
public class book
{
    /** */
    public string book name;
    
    /** */
    public Object book id;
}
