//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : bookthbrtg.java
//  @ Date : 15-04-2024
//  @ Author : 
//
//




/** */
public class bookthbrtg
{
}
