//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : supplier.java
//  @ Date : 15-04-2024
//  @ Author : 
//
//




/** */
public class supplier
{
    /** */
    public string address;
    
    /** */
    public visitor Unnamed1;
    
    /** */
    public books Unnamed2;
    
    /** */
    public void addNewbooks()
    {
    
    }
    
    /** */
    public void supplybook()
    {
    
    }
}
