//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : visitor.java
//  @ Date : 15-04-2024
//  @ Author : 
//
//




/** */
public class visitor
{
    /** */
    public string email;
    
    /** */
    public string password;
    
    /** */
    public supplier Unnamed1;
    
    /** */
    public void sign in()
    {
    
    }
    
    /** */
    public void search book()
    {
    
    }
    
    /** */
    public void create account to get full details()
    {
    
    }
}
